URL = "http://0.0.0.0:5001/"
STRING_URL = URL + "string"
FILE_URL = URL + "file"

# MODULE INFO RETRIEVAL

MODULE_INFO_RETRIEVAL_URL = URL + "module-info"
MODULE_INFO_RETRIEVAL_DATASET_KEY = "dataset"
MODULE_INFO_RETRIEVAL_MODULES_KEY = "modules"

# GRAPH RETRIEVAL

GRAPH_RETRIEVAL_URL = URL + "graphs"
GRAPH_RETRIEVAL_DATASET_KEY = "dataset"
GRAPH_RETRIEVAL_MODULES_KEY = "modules"
GRAPH_RETRIEVAL_PDB_KEY = "pdb"
