URL = "http://0.0.0.0:5001/"
STRING_URL = URL + "string"
FILE_URL = URL + "file"
GRAPHS_URL = URL + "graphs"

# MODULE INFO RETRIEVAL

MODULE_INFO_RETRIEVAL_URL = URL + "module-info"
MODULE_INFO_RETRIEVAL_DATASET_KEY = "dataset"
MODULE_INFO_RETRIEVAL_MODULES_KEY = "modules"
